sudo: required

services:
  - docker


before_install:
  - docker build -t usmanbrackets/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true usmanbrackets/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-1.amazonaws.com"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-979081741284"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: "$Access_key_id"
  secret_access_key: "$Secret_access_key"
